// integration/supabase/client.ts
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer NEXT_PUBLIC_* for client-side vars, but accept legacy names if you haven't renamed your .env yet.
const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ??
  process.env.SUPABASE_URL ??
  'https://jwvcgawjkltegcnyyryo.supabase.co';

const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
  process.env.SUPABASE_ANON_KEY ??
  '';

// Export supabase client. Guard localStorage for SSR environments.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? (window.localStorage as any) : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
